In [1]:
import pandas as pd
from pprint import pprint
import numpy as np
from IPython.display import clear_output

In [2]:
pd.options.display.max_columns = 999

In [3]:
data = pd.read_pickle("senate_master")

In [4]:
data.shape

(133103, 31)

In [5]:
data.sample()

,_id,actions,activeVersion,additionalSponsors,adopted,amendmentVersions,amendments,approvalMessage,basePrintNo,basePrintNoStr,billType,calendars,committeeAgendas,milestones,pastCommittees,previousVersions,printNo,programInfo,publishStatusMap,publishedDateTime,session,signed,sponsor,status,substitutedBy,summary,title,vetoMessages,vetoed,votes,year
132048,5b1c1b185a67a40cd349d4d1,{'items': [{'billId': {'basePrintNo': 'A10804'...,A,"{'items': [], 'size': 0}",False,"{'items': ['', 'A'], 'size': 2}","{'items': {'': {'basePrintNo': 'A10804', 'sess...",None,A10804,A10804-2017,"{'chamber': 'ASSEMBLY', 'desc': 'Assembly', 'r...","{'items': [], 'size': 0}","{'items': [], 'size': 0}","{'items': [{'statusType': 'IN_ASSEMBLY_COMM', ...","{'items': [{'chamber': 'ASSEMBLY', 'name': 'Co...","{'items': [], 'size': 0}",A10804A,None,"{'items': {'': {'version': '', 'published': Tr...",2018-05-18T11:14:36,2017,False,"{'member': {'memberId': 533, 'sessionMemberId'...","{'statusType': 'IN_ASSEMBLY_COMM', 'statusDesc...",None,Establishes licensing requirements for energy ...,Establishes licensing requirements for energy ...,"{'items': [], 'size': 0}",False,"{'items': [], 'size': 0}",2018

In [6]:
data_sponsor = data[['_id','sponsor']]
data_sponsor.sample(10)

,_id,sponsor
76777,5b1c174f5a67a40cd348fcea,"{'member': {'memberId': 575, 'sessionMemberId'..."
38822,5b1c14a55a67a40cd34868a7,"{'member': {'memberId': 607, 'sessionMemberId'..."
18867,5b1c130d5a67a40cd3481ab4,"{'member': {'memberId': 399, 'sessionMemberId'..."
5480,5b1c12435a67a40cd347e669,"{'member': {'memberId': 414, 'sessionMemberId'..."
115878,5b1c1a2a5a67a40cd34995a7,"{'member': {'memberId': 599, 'sessionMemberId'..."
42781,5b1c14e85a67a40cd348781e,"{'member': {'memberId': 424, 'sessionMemberId'..."
57368,5b1c16075a67a40cd348b119,"{'member': {'memberId': 385, 'sessionMemberId'..."
97409,5b1c18ea5a67a40cd3494d82,"{'member': {'memberId': 439, 'sessionMemberId'..."
76500,5b1c174f5a67a40cd348fbd5,"{'member': {'memberId': 429, 'sessionMemberId'..."
42223,5b1c14d75a67a40cd34875f0,"{'member': {'memberId': 410, 'sessionMemberId'..."

In [7]:
def get_rando():
    rando = np.random.randint(50000)
    print(f"rando: {rando}")
    pprint(data_sponsor.iloc[rando]['sponsor'])
#     print(data_sponsor.iloc[rando])
get_rando()

rando: 38248
{'budget': False,
 'member': {'alternate': False,
            'chamber': 'ASSEMBLY',
            'districtCode': 143,
            'fullName': 'Dennis H. Gabryszak',
            'imgName': 'no_image.jpg',
            'memberId': 593,
            'sessionMemberId': 420,
            'sessionYear': 2011,
            'shortName': 'GABRYSZAK'},
 'rules': False}

In [8]:
def get_rando():
    rando = np.random.randint(50000)
    print(f"rando: {rando}")
    pprint(data_sponsor.iloc[rando]['sponsor'])
#     print(data_sponsor.iloc[rando])
get_rando()

rando: 6054
{'budget': False,
 'member': {'alternate': False,
            'chamber': 'SENATE',
            'districtCode': 32,
            'fullName': 'Ruben Diaz',
            'imgName': '421_ruben_diaz.jpg',
            'memberId': 421,
            'sessionMemberId': 51,
            'sessionYear': 2009,
            'shortName': 'DIAZ'},
 'rules': False}

In [9]:
new_list = []
counter = 0
for idx,row in data_sponsor.iterrows():
#     pprint(row)
    counter += 1
#     if counter > 15:
#         break
    if counter % 20000 == 0:
#         clear_output()
        print(f"counter: {counter}")
        
#     pprint(row)
    
    if ( row['sponsor'] == None):
        amend_info = { '_id':row['_id']
                          ,'chamber': ''
                          , 'distictCode':np.NaN
                         ,'fullName': ''
                         , 'sessionYear': np.NaN
                         ,'shortName': ''
                         }
    elif (row['sponsor']['member'] is None):
        if row['sponsor']['budget']:
            amend_info = { '_id':row['_id']
                          ,'chamber': 'budget'
                          , 'distictCode': np.NaN
                         ,'fullName':'budget'
                         , 'sessionYear': np.NaN
                         ,'shortName': 'budget'
                         }
        elif row['sponsor']['rules']:
            amend_info = { '_id':row['_id']
                          ,'chamber': 'rules'
                          , 'distictCode':np.NaN
                         ,'fullName': 'rules'
                         , 'sessionYear': np.NaN
                         ,'shortName': 'rules'
                         }
            

    else:

        member = row['sponsor']['member']
        amend_info = { '_id':row['_id']
                      ,'chamber': member['chamber']
                      , 'distictCode': int(member['districtCode'])
                     ,'fullName': member['fullName']
                     , 'sessionYear': int(member['sessionYear'])
                     ,'shortName': member['shortName']
                     }

    new_list.append(amend_info)
    
    
data_sponsors = pd.DataFrame(new_list)
data_sponsors.sample(10)

counter: 20000
counter: 40000
counter: 60000
counter: 80000
counter: 100000
counter: 120000

,_id,chamber,distictCode,fullName,sessionYear,shortName
51961,5b1c15795a67a40cd3489bfa,SENATE,21.0,Kevin S. Parker,2011.0,PARKER
112886,5b1c19fd5a67a40cd34989f7,SENATE,28.0,Liz Krueger,2017.0,KRUEGER
92799,5b1c189a5a67a40cd3493b80,ASSEMBLY,1.0,Fred Thiele,2015.0,THIELE
6521,5b1c125a5a67a40cd347ea7a,SENATE,37.0,Suzi Oppenheimer,2009.0,OPPENHEIMER
73215,5b1c17125a67a40cd348ef00,ASSEMBLY,70.0,Keith L.T. Wright,2013.0,WRIGHT
48255,5b1c153b5a67a40cd3488d80,ASSEMBLY,64.0,Sheldon Silver,2011.0,SILVER
78074,5b1c175e5a67a40cd34901fb,SENATE,42.0,John J. Bonacic,2013.0,BONACIC
75555,5b1c17415a67a40cd348f824,SENATE,63.0,Timothy M. Kennedy,2013.0,KENNEDY
69098,5b1c16cc5a67a40cd348deeb,ASSEMBLY,101.0,Kevin Cahill,2013.0,CAHILL
749,5b1c11ca5a67a40cd347d3ee,SENATE,28.0,José M. Serrano,2009.0,SERRANO

In [10]:
pd.to_pickle(data_sponsors,"data_sponsors")